import 'package:musicmaniac/models/user.model.dart';

const firstnames = <String>[
  "Eki", "Joshua", "Ayo", "Jesutobi", "Samuel", 
  "Timilehin", "Daniel", "Mercy", "Tunde", "Celeb"
];

const lastnames = <String>[
  "Agho", "Famuyiwa", "Bamidele", "Ogunjobi", "Alice", 
  "Afolabi", "Daniels", "Anuoluwapo", "Johnsons", "Thick"
];

List<User> users = <User>[
  User(
    firstname: firstnames[0],
    lastname: lastnames[0],
    email: 'support@musicmaniac.com',
    username: 'user-1-names',
    avatar: "assets/avatars/1.png",
    genre: "hiphop",
    phone: "",
    password: "",
    role: "artiste",
    rank: 1,
  ),
  User(
    firstname: firstnames[1],
    lastname: lastnames[1],
    email: 'support@musicmaniac.com',
    username: 'user-1-names',
    avatar: "assets/avatars/2.png",
    genre: "hiphop",
    phone: "",
    password: "",
    role: "sponsore",
    rank: 2,
  ),
  User(
    firstname: firstnames[2],
    lastname: lastnames[2],
    email: 'support@musicmaniac.com',
    username: 'user-1-names',
    avatar: "assets/avatars/3.png",
    genre: "hiphop",
    phone: "",
    password: "",
    role: "fan",
    rank: 3,
  ),
  User(
    firstname: firstnames[3],
    lastname: lastnames[3],
    email: 'support@musicmaniac.com',
    username: 'user-1-names',
    avatar: "assets/avatars/4.png",
    genre: "hiphop",
    phone: "",
    password: "",
    role: "artiste",
    rank: 4,
  ),
  User(
    firstname: firstnames[4],
    lastname: lastnames[4],
    email: 'support@musicmaniac.com',
    username: 'user-1-names',
    avatar: "assets/avatars/5.png",
    genre: "hiphop",
    phone: "",
    password: "",
    role: "artiste",
    rank: 5,
  ),
  User(
    firstname: firstnames[5],
    lastname: lastnames[5],
    email: 'support@musicmaniac.com',
    username: 'user-6-names',
    avatar: "assets/avatars/6.png",
    genre: "hiphop",
    phone: "",
    password: "",
    role: "sponsore",
    rank: 6,
  ),
  User(
    firstname: firstnames[6],
    lastname: lastnames[6],
    email: 'support@musicmaniac.com',
    username: 'user-7-names',
    avatar: "assets/avatars/7.png",
    genre: "hiphop",
    phone: "",
    password: "",
    role: "artiste",
    rank: 7,
  ),
  User(
    firstname: firstnames[7],
    lastname: lastnames[7],
    email: 'support@musicmaniac.com',
    username: 'user-8-names',
    avatar: "assets/avatars/8.png",
    genre: "hiphop",
    phone: "",
    password: "",
    role: "fan",
    rank: 8,
  ),
  User(
    firstname: firstnames[8],
    lastname: lastnames[8],
    email: 'support@musicmaniac.com',
    username: 'user-9-names',
    avatar: "assets/avatars/9.png",
    genre: "hiphop",
    phone: "",
    password: "",
    role: "artiste",
    rank: 9,
  ),
  User(
    firstname: firstnames[9],
    lastname: lastnames[9],
    email: 'support@musicmaniac.com',
    username: 'user-10-names',
    avatar: "assets/avatars/10.png",
    genre: "hiphop",
    phone: "",
    password: "",
    role: "artiste",
    rank: 10,
  ),
];



